### ISSUE TITLE
Training type

### ISSUE THREAD

**Issue by Tywors** [chaiyujin/dctts-pytorch#3]
Hi! One question,
Its obligatory train in Text2Mel and SSRN? Or if only train one of this works?

Thanks!

**Comment by chaiyujin** [comment]
Both of them should be trained.  Result of Text2Mel is not full melspectrogram, so you cannot directly inverse it.
Following is the pipeline

text -> [TextMel] -> reduced mel spectrogram -> [SSRN] -> linear spectrogram -> [Griffin-Lim] -> wav

**Comment by Tywors** [comment]
Thanks!
And your training model in dropbox is textmel or SSRN, because need this two files for sy thesis.
If i clone your file to text2mel and ssrn folder work. But i don't know if the best way.

Thaks

**Comment by chaiyujin** [comment]
I don't remember what I put in that logdir.7z. And I delete it locally. Could you offer me a folder structure?  Both pre-trained Text2Mel and SSRN models are supposed to be in that 7zip file.

**Comment by Tywors** [comment]
Yes, i confused with my 7zip.
I will publich my results with my voice in spanish 💃  (1-2month)
Goog git!
