### ISSUE TITLE
Multiple GPU

### ISSUE THREAD

**Issue by Tywors** [chaiyujin/dctts-pytorch#4]
Hello, 

how i can incorporate the DataParallel in this project?
model = nn.DataParallel(model)

thanks

**Comment by chaiyujin** [comment]
@Tywors 
Insert `graph = nn.DataParallel(graph)` at  https://github.com/chaiyujin/dctts-pytorch/blob/b69b9f63fe83a883c2f94fd93be431ead9ec1654/pkg/train.py#L127  
`"graph" : graph.moduel.state_dict()` at https://github.com/chaiyujin/dctts-pytorch/blob/b69b9f63fe83a883c2f94fd93be431ead9ec1654/pkg/train.py#L62

**Comment by Tywors** [comment]
Thanks for your answer!

With this change, this is the result in train:

`File "main.py", line 62, in <module>
    main()
  File "main.py", line 47, in main
    train(args.module, args.load)
  File "/content/dctts-pytorch/pkg/train.py", line 54, in train
    train_text2mel(load_trained)
  File "/content/dctts-pytorch/pkg/train.py", line 177, in train_text2mel
    atten_mask = torch.ones_like(graph.attention)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'attention'`

any suggestion?

**Comment by chaiyujin** [comment]
@Tywors 
Actually, after `graph = nn.DataParallel(graph)`, the original graph is wrapped by a DataParallel. It's possible to access original graph by `graph.module`.
Maybe you have to change `graph` to `graph.module`  at several places.
I''m sorry that I don't have time to help you do all changes, because I'm focusing on my private project.

**Comment by Tywors** [comment]
Thanks for your time!
I continue trying!

**Comment by lxy444** [comment]
> Thanks for your time!
> I continue trying!

Have you solved the problem?
